name: Deploy Auth Service

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish .NET application
        run: |
          dotnet publish -c Release -o ./publish
        working-directory: ./

      - name: Debug Secrets
        run: |
          echo "Host: ${{ secrets.EC2_HOST }}"
          echo "SSH Key starts with: $(echo '${{ secrets.EC2_SSH_KEY }}' | head -n 1)"

      - name: Copy published files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./publish/*"
          target: "/home/ubuntu/e2epayment_auth"
          strip_components: 1
          debug: true

      - name: Restart service on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart e2epayments_auth.service
